//
//  NLContentType.swift
//  NetworkManager
//
//  Created by yasinkbas on 2.07.2020.
//  Copyright © 2020 Yasin Akbaş. All rights reserved.
//

import Foundation

// https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types/Common_types
public enum NLContentType {
    case aac
    case abw
    case arc
    case avi
    case azw
    case bin
    case bmp
    case bz
    case bz2
    case csh
    case css
    case csv
    case doc
    case docx
    case eot
    case epub
    case gz
    case gif
    case htm
    case html
    case ico
    case ics
    case jar
    case jpeg
    case jpg
    case js
    case json
    case jsonld
    case mid
    case midi
    case mjs
    case mp3
    case mpeg
    case mpkg
    case odp
    case ods
    case odt
    case oga
    case ogv
    case ogx
    case opus
    case otf
    case png
    case pdf
    case php
    case plain
    case ppt
    case pptx
    case rar
    case rtf
    case sh
    case svg
    case swf
    case tar
    case text
    case tif
    case tiff
    case ts
    case ttf
    case txt
    case vsd
    case wav
    case weba
    case webm
    case webp
    case woff
    case woff2
    case xhtml
    case xls
    case xlsx
    case xml
    case xul
    case zip
    case _3gpAudio
    case _3gpVideo
    case _3g2Audio
    case _3g2Video
    case _7z
    case custom(String)
    
    public var mime: String {
        switch self {
        case .aac:
            return "audio/aac"
        case .abw:
            return "application/x-abiword"
        case .arc:
            return "application/x-freearc"
        case .avi:
            return "video/x-msvideo"
        case .azw:
            return "application/vnd.amazon.ebook"
        case .bin:
            return "application/octet-stream"
        case .bmp:
            return "image/bmp"
        case .bz:
            return "application/x-bzip"
        case .bz2:
            return "application/x-bzip2"
        case .csh:
            return "application/x-csh"
        case .css:
            return "text/css"
        case .csv:
            return "text/csv"
        case .doc:
            return "application/msword"
        case .docx:
            return "application/vnd.openxmlformats-officedocument.wordprocessingml.document"
        case .eot:
            return "application/vnd.ms-fontobject"
        case .epub:
            return "application/epub+zip"
        case .gz:
            return "application/gzip"
        case .gif:
            return "image/gif"
        case .htm, .html:
            return "text/html"
        case .ico:
            return "image/vnd.microsoft.icon"
        case .ics:
            return "text/calendar"
        case .jar:
            return "application/java-archive"
        case .jpeg, .jpg:
            return "image/jpeg"
        case .js, .mjs:
            return "text/javascript"
        case .json:
            return "application/json"
        case .jsonld:
            return "application/ld+json"
        case .mid, .midi:
            return "audio/midi"
        case .mp3:
            return "audio/mpeg"
        case .mpeg:
            return "video/mpeg"
        case .mpkg:
            return "application/vnd.apple.installer+xml"
        case .odp:
            return "application/vnd.oasis.opendocument.presentation"
        case .ods:
            return "application/vnd.oasis.opendocument.spreadsheet"
        case .odt:
            return "application/vnd.oasis.opendocument.text"
        case .oga:
            return "audio/ogg"
        case .ogv:
            return "video/ogg"
        case .ogx:
            return "application/ogg"
        case .opus:
            return "audio/opus"
        case .otf:
            return "font/otf"
        case .png:
            return "image/png"
        case .pdf:
            return "application/pdf"
        case .php:
            return "application/x-httpd-php"
        case .ppt:
            return "application/vnd.ms-powerpoint"
        case .pptx:
            return "application/vnd.openxmlformats-officedocument.presentationml.presentation"
        case .rar:
            return "application/vnd.rar"
        case .rtf:
            return "application/rtf"
        case .sh:
            return "application/x-sh"
        case .svg:
            return "image/svg+xml"
        case .swf:
            return "application/x-shockwave-flash"
        case .tar:
            return "application/x-tar"
        case .tif, .tiff:
            return "image/tiff"
        case .ts:
            return "video/mp2t"
        case .ttf:
            return "font/ttf"
        case .txt, .text, .plain:
            return "text/plain"
        case .vsd:
            return "application/vnd.visio"
        case .wav:
            return "audio/wav"
        case .weba:
            return "audio/webm"
        case .webm:
            return "video/webm"
        case .webp:
            return "image/webp"
        case .woff:
            return "font/woff"
        case .woff2:
            return "font/woff2"
        case .xhtml:
            return "application/xhtml+xml"
        case .xls:
            return "application/vnd.ms-excel"
        case .xlsx:
            return "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
        case .xml:
            return "application/xml"
        case .xul:
            return "application/vnd.mozilla.xul+xml"
        case .zip:
            return "application/zip"
        case ._3gpAudio:
            return "audio/3gpp"
        case ._3gpVideo:
            return "video/3gpp"
        case ._3g2Audio:
            return "audio/3gpp2"
        case ._3g2Video:
            return "video/3gpp2"
        case ._7z:
            return "application/x-7z-compressed"
        case .custom(let mime):
            return mime
        }
    }
}
